name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- develop

stages:
  - stage: ci_build_simplevat
    displayName: CI Build for SimpleVAT
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: build
      displayName: Build & Push SimpleVAT Application
      timeoutInMinutes: 30

      steps:
      - task: Docker@2
        displayName: Docker Build & Push
        inputs:
          containerRegistry: 'DataInnAzureContainerRegistryConnection'
          repository: 'simplevat-frontend'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            0.0.3-alpha-$(Build.BuildId)




